### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by CodeWitchBella** [CodeWitchBella/yoga-wasm#1]
Following are things I want to do with this module until I can consider it "done"

- [x] make basic functionality work (be able to render simple pdf using react-pdf)
- [x] do not inline .wasm file into .js bundle
- [x] make [official tests](https://github.com/facebook/yoga/tree/master/javascript/tests) test suite run
- [x] make those tests pass
- [x] update yoga sources to latest upstream
- [x] also add stuff not covered by tests (mostly getters)
- [x] remove most of custom adapters in JS and instead export methods directly from source
- [ ] ~use standard tools like prettier and eslint~
- [x] update tooling

**Comment by CodeWitchBella** [comment]
Everything except using eslint and prettier is done and I am not doing that because most of code is just copied directly from upstream yoga bindings
